name: Build and Publish Docker

on:
  push:
    tags:
      - '[0-9]*.*.*'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set git env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build and publish image antmoc-ci
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        VCS_URL: $(git config --get remote.origin.url)
        VCS_REF: $(git rev-parse --short HEAD)
        SPACK_IMAGE: spack/ubuntu-bionic
        SPACK_VERSION: latest
      with:
        name: leavesask/antmoc-ci
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: SPACK_IMAGE,SPACK_VERSION,BUILD_DATE,VCS_URL,VCS_REF
        buildoptions: "--compress"
        tags: ${{ env.RELEASE_VERSION }}
